In [ ]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Kaggle credentials set.
Kaggle credentials successfully validated.

In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

sharankumare_mcq_train_path = kagglehub.dataset_download('sharankumare/mcq-train')
illuminatep_deberta_v3_plain_transformers_large_1_path = kagglehub.model_download('illuminatep/deberta-v3-plain/Transformers/large/1')

print('Data source import complete.')

Downloading to /root/.cache/kagglehub/datasets/sharankumare/mcq-train/1.archive...

100%|██████████| 324k/324k [00:00<00:00, 85.4MB/s]

Extracting files...

Downloading 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Downloading to /root/.cache/kagglehub/models/illuminatep/deberta-v3-plain/Transformers/large/1/config.json...

100%|██████████| 945/945 [00:00<00:00, 704kB/s]

Downloading to /root/.cache/kagglehub/models/illuminatep/deberta-v3-plain/Transformers/large/1/tokenizer_config.json...

100%|██████████| 562/562 [00:00<00:00, 1.66MB/s]

Downloading to /root/.cache/kagglehub/models/illuminatep/deberta-v3-plain/Transformers/large/1/tokenizer.json...

  0%|          | 0.00/7.95M [00:00<?, ?B/s]

Downloading to /root/.cache/kagglehub/models/illuminatep/deberta-v3-plain/Transformers/large/1/spm.model...
Downloading to /root/.cache/kagglehub/models/illuminatep/deberta-v3-plain/Transformers/large/1/model.safetensors...

  0%|          | 0.00/2.35M [00:00<?, ?B/s]


  0%|          | 0.00/1.62G [00:00<?, ?B/s]
 13%|█▎        | 1.00M/7.95M [00:00<00:03, 2.24MB/s]
 38%|███▊      | 3.00M/7.95M [00:00<00:00, 6.00MB/s]
100%|██████████| 7.95M/7.95M [00:00<00:00, 11.2MB/s]



  0%|          | 1.00M/1.62G [00:00<10:40, 2.71MB/s]

100%|██████████| 2.35M/2.35M [00:00<00:00, 5.09MB/s]



  0%|          | 3.00M/1.62G [00:00<03:51, 7.47MB/s]


  0%|          | 8.00M/1.62G [00:00<01:27, 19.8MB/s]


  1%|          | 14.0M/1.62G [00:00<00:55, 31.0MB/s]


  1%|          | 20.0M/1.62G [00:00<00:44, 38.9MB/s]


  2%|▏         | 26.0M/1.62G [00:00<00:37, 45.0MB/s]


  2%|▏         | 32.0M/1.62G [00:01<00:34, 49.1MB/s]


  2%|▏         | 38.0M/1.62G [00:01<00:32, 51.8MB/s]


  3%|▎         | 44.0M/1.62G [00:01<00:31, 54.3MB/s]


  3%|▎         | 50.0M/1.62G [00:01<00:30, 54.7MB/s]


  3%|▎         | 56.0M/1.62G [00:01<00:30, 55.6MB/s]


  4%|▎         | 62.0M/1.62G [00:01<00:29, 56.2MB/s]


  4%|▍         | 68.0M/1.62G [00:01<00:28, 57.5MB/s]


  4%|▍         | 74.0M/1.62G [00:01<00:28, 57.7MB/s]


  5%|▍         | 80.0M/1.62G [00:01<00:28, 58.0MB/s]


  5%|▌         | 86.0M/1.62G [00:02<00:28, 57.6MB/s]


  6%|▌         | 92.0M/1.62G [00:02<00:27, 58.9MB/s]


  6%|▌         | 98.0M/1.62G [00:02<00:28, 57.6MB/s]


  6%|▋         | 104M/1.62G [00:02<00:27, 58.2MB/s]


  7%|▋         | 110M/1.62G [00:02<00:27, 58.5MB/s]


  7%|▋         | 116M/1.62G [00:02<00:28, 57.2MB/s]


  7%|▋         | 122M/1.62G [00:02<00:27, 58.8MB/s]


  8%|▊         | 128M/1.62G [00:02<00:27, 59.3MB/s]


  8%|▊         | 134M/1.62G [00:02<00:27, 57.7MB/s]


  8%|▊         | 140M/1.62G [00:02<00:27, 58.2MB/s]


  9%|▉         | 146M/1.62G [00:03<00:26, 59.0MB/s]


  9%|▉         | 152M/1.62G [00:03<00:26, 58.5MB/s]


 10%|▉         | 158M/1.62G [00:03<00:27, 57.2MB/s]


 10%|▉         | 164M/1.62G [00:03<00:26, 58.8MB/s]


 10%|█         | 170M/1.62G [00:03<00:26, 58.2MB/s]


 11%|█         | 176M/1.62G [00:03<00:27, 57.1MB/s]


 11%|█         | 182M/1.62G [00:03<00:26, 58.6MB/s]


 11%|█▏        | 188M/1.62G [00:03<00:26, 58.4MB/s]


 12%|█▏        | 194M/1.62G [00:03<00:26, 57.5MB/s]


 12%|█▏        | 200M/1.62G [00:04<00:26, 58.3MB/s]


 12%|█▏        | 206M/1.62G [00:04<00:25, 58.8MB/s]


 13%|█▎        | 212M/1.62G [00:04<00:26, 57.1MB/s]


 13%|█▎        | 218M/1.62G [00:04<00:25, 58.4MB/s]


 14%|█▎        | 224M/1.62G [00:04<00:25, 59.0MB/s]


 14%|█▍        | 231M/1.62G [00:04<00:25, 58.1MB/s]


 14%|█▍        | 238M/1.62G [00:04<00:25, 57.7MB/s]


 15%|█▍        | 245M/1.62G [00:04<00:25, 58.2MB/s]


 15%|█▌        | 251M/1.62G [00:05<00:28, 52.4MB/s]


 16%|█▌        | 257M/1.62G [00:05<00:29, 49.8MB/s]


 16%|█▌        | 262M/1.62G [00:05<00:29, 49.1MB/s]


 16%|█▌        | 269M/1.62G [00:05<00:28, 51.2MB/s]


 17%|█▋        | 276M/1.62G [00:05<00:27, 53.0MB/s]


 17%|█▋        | 284M/1.62G [00:05<00:25, 55.7MB/s]


 18%|█▊        | 291M/1.62G [00:05<00:25, 56.1MB/s]


 18%|█▊        | 298M/1.62G [00:05<00:25, 56.4MB/s]


 18%|█▊        | 305M/1.62G [00:06<00:25, 56.4MB/s]


 19%|█▉        | 313M/1.62G [00:06<00:24, 58.0MB/s]


 19%|█▉        | 320M/1.62G [00:06<00:24, 57.6MB/s]


 20%|█▉        | 327M/1.62G [00:06<00:24, 57.6MB/s]


 20%|██        | 335M/1.62G [00:06<00:23, 58.7MB/s]


 21%|██        | 342M/1.62G [00:06<00:23, 58.2MB/s]


 21%|██        | 348M/1.62G [00:07<01:27, 15.6MB/s]


 21%|██▏       | 353M/1.62G [00:08<02:01, 11.3MB/s]


 22%|██▏       | 363M/1.62G [00:08<01:18, 17.3MB/s]


 22%|██▏       | 371M/1.62G [00:09<01:00, 22.4MB/s]


 23%|██▎       | 378M/1.62G [00:09<00:49, 27.0MB/s]


 23%|██▎       | 385M/1.62G [00:09<00:41, 31.9MB/s]


 24%|██▎       | 393M/1.62G [00:09<00:35, 37.5MB/s]


 24%|██▍       | 400M/1.62G [00:09<00:31, 41.6MB/s]


 25%|██▍       | 407M/1.62G [00:09<00:28, 45.5MB/s]


 25%|██▌       | 415M/1.62G [00:09<00:26, 49.4MB/s]


 25%|██▌       | 422M/1.62G [00:10<00:25, 51.4MB/s]


 26%|██▌       | 429M/1.62G [00:10<00:24, 52.9MB/s]


 26%|██▋       | 436M/1.62G [00:10<00:23, 54.7MB/s]


 27%|██▋       | 444M/1.62G [00:10<00:22, 56.1MB/s]


 27%|██▋       | 451M/1.62G [00:10<00:22, 56.5MB/s]


 28%|██▊       | 458M/1.62G [00:10<00:21, 57.7MB/s]


 28%|██▊       | 465M/1.62G [00:10<00:21, 57.4MB/s]


 29%|██▊       | 473M/1.62G [00:10<00:21, 58.5MB/s]


 29%|██▉       | 480M/1.62G [00:11<00:21, 58.1MB/s]


 29%|██▉       | 487M/1.62G [00:11<00:20, 58.4MB/s]


 30%|██▉       | 495M/1.62G [00:11<00:20, 58.7MB/s]


 30%|███       | 502M/1.62G [00:11<00:20, 58.6MB/s]


 31%|███       | 509M/1.62G [00:11<00:20, 58.7MB/s]


 31%|███       | 517M/1.62G [00:11<00:20, 59.1MB/s]


 32%|███▏      | 524M/1.62G [00:11<00:20, 58.7MB/s]


 32%|███▏      | 531M/1.62G [00:11<00:20, 58.2MB/s]


 32%|███▏      | 538M/1.62G [00:12<00:20, 58.4MB/s]


 33%|███▎      | 546M/1.62G [00:12<00:19, 59.0MB/s]


 33%|███▎      | 553M/1.62G [00:12<00:19, 58.8MB/s]


 34%|███▍      | 560M/1.62G [00:12<00:19, 59.0MB/s]


 34%|███▍      | 568M/1.62G [00:12<00:19, 59.0MB/s]


 35%|███▍      | 575M/1.62G [00:12<00:19, 58.9MB/s]


 35%|███▌      | 582M/1.62G [00:12<00:19, 59.0MB/s]


 36%|███▌      | 589M/1.62G [00:12<00:19, 58.5MB/s]


 36%|███▌      | 597M/1.62G [00:13<00:18, 59.1MB/s]


 36%|███▋      | 604M/1.62G [00:13<00:18, 58.5MB/s]


 37%|███▋      | 611M/1.62G [00:13<00:18, 58.7MB/s]


 37%|███▋      | 619M/1.62G [00:13<00:18, 58.8MB/s]


 38%|███▊      | 626M/1.62G [00:13<00:18, 58.8MB/s]


 38%|███▊      | 633M/1.62G [00:13<00:18, 59.0MB/s]


 39%|███▊      | 641M/1.62G [00:13<00:18, 59.0MB/s]


 39%|███▉      | 648M/1.62G [00:14<00:17, 59.0MB/s]


 40%|███▉      | 655M/1.62G [00:14<00:18, 57.9MB/s]


 40%|███▉      | 662M/1.62G [00:14<00:17, 58.6MB/s]


 40%|████      | 670M/1.62G [00:14<00:17, 59.1MB/s]


 41%|████      | 677M/1.62G [00:14<00:17, 58.9MB/s]


 41%|████▏     | 684M/1.62G [00:14<00:17, 59.1MB/s]


 42%|████▏     | 692M/1.62G [00:14<00:17, 59.1MB/s]


 42%|████▏     | 699M/1.62G [00:14<00:17, 58.9MB/s]


 43%|████▎     | 706M/1.62G [00:15<00:17, 58.3MB/s]


 43%|████▎     | 713M/1.62G [00:15<00:16, 58.7MB/s]


 44%|████▎     | 721M/1.62G [00:15<00:16, 59.0MB/s]


 44%|████▍     | 728M/1.62G [00:15<00:16, 58.6MB/s]


 44%|████▍     | 734M/1.62G [00:15<00:17, 55.3MB/s]


 45%|████▍     | 740M/1.62G [00:15<00:19, 49.7MB/s]


 45%|████▍     | 745M/1.62G [00:15<00:19, 50.2MB/s]


 45%|████▌     | 752M/1.62G [00:15<00:17, 53.1MB/s]


 46%|████▌     | 759M/1.62G [00:16<00:17, 54.2MB/s]


 46%|████▋     | 766M/1.62G [00:16<00:17, 54.7MB/s]


 47%|████▋     | 773M/1.62G [00:16<00:16, 55.9MB/s]


 47%|████▋     | 781M/1.62G [00:16<00:15, 58.0MB/s]


 48%|████▊     | 788M/1.62G [00:16<00:15, 57.8MB/s]


 48%|████▊     | 795M/1.62G [00:16<00:15, 57.5MB/s]


 49%|████▊     | 803M/1.62G [00:16<00:15, 59.2MB/s]


 49%|████▉     | 810M/1.62G [00:17<00:15, 58.6MB/s]


 49%|████▉     | 817M/1.62G [00:17<00:15, 58.2MB/s]


 50%|████▉     | 824M/1.62G [00:17<00:15, 57.9MB/s]


 50%|█████     | 832M/1.62G [00:17<00:14, 59.3MB/s]


 51%|█████     | 839M/1.62G [00:17<00:14, 58.7MB/s]


 51%|█████     | 846M/1.62G [00:17<00:14, 58.4MB/s]


 52%|█████▏    | 853M/1.62G [00:17<00:13, 62.1MB/s]


 52%|█████▏    | 859M/1.62G [00:17<00:13, 60.7MB/s]


 52%|█████▏    | 865M/1.62G [00:18<00:14, 58.1MB/s]


 53%|█████▎    | 872M/1.62G [00:18<00:14, 57.9MB/s]


 53%|█████▎    | 879M/1.62G [00:18<00:14, 57.9MB/s]


 54%|█████▎    | 886M/1.62G [00:18<00:13, 57.7MB/s]


 54%|█████▍    | 893M/1.62G [00:18<00:13, 61.5MB/s]


 54%|█████▍    | 899M/1.62G [00:18<00:13, 60.2MB/s]


 55%|█████▍    | 905M/1.62G [00:18<00:13, 57.5MB/s]


 55%|█████▌    | 912M/1.62G [00:18<00:13, 57.8MB/s]


 56%|█████▌    | 919M/1.62G [00:18<00:13, 57.9MB/s]


 56%|█████▌    | 926M/1.62G [00:19<00:12, 61.6MB/s]


 56%|█████▋    | 932M/1.62G [00:19<00:12, 60.3MB/s]


 57%|█████▋    | 938M/1.62G [00:19<00:13, 57.6MB/s]


 57%|█████▋    | 945M/1.62G [00:19<00:12, 57.7MB/s]


 57%|█████▋    | 952M/1.62G [00:19<00:12, 57.8MB/s]


 58%|█████▊    | 959M/1.62G [00:19<00:12, 57.6MB/s]


 58%|█████▊    | 966M/1.62G [00:19<00:11, 61.3MB/s]


 59%|█████▊    | 972M/1.62G [00:19<00:11, 60.2MB/s]


 59%|█████▉    | 978M/1.62G [00:20<00:12, 57.6MB/s]


 59%|█████▉    | 985M/1.62G [00:20<00:12, 56.2MB/s]


 60%|█████▉    | 991M/1.62G [00:20<00:12, 54.0MB/s]


 60%|██████    | 998M/1.62G [00:20<00:12, 54.6MB/s]


 61%|██████    | 0.98G/1.62G [00:20<00:12, 55.5MB/s]


 61%|██████    | 0.99G/1.62G [00:20<00:12, 55.9MB/s]


 62%|██████▏   | 1.00G/1.62G [00:20<00:11, 56.2MB/s]


 62%|██████▏   | 1.00G/1.62G [00:20<00:11, 58.2MB/s]


 62%|██████▏   | 1.01G/1.62G [00:21<00:11, 57.9MB/s]


 63%|██████▎   | 1.02G/1.62G [00:21<00:11, 57.8MB/s]


 63%|██████▎   | 1.02G/1.62G [00:21<00:11, 57.4MB/s]


 64%|██████▍   | 1.03G/1.62G [00:21<00:10, 59.0MB/s]


 64%|██████▍   | 1.04G/1.62G [00:21<00:10, 58.4MB/s]


 65%|██████▍   | 1.04G/1.62G [00:21<00:10, 56.9MB/s]


 65%|██████▍   | 1.05G/1.62G [00:21<00:11, 53.6MB/s]


 65%|██████▌   | 1.06G/1.62G [00:21<00:11, 51.7MB/s]


 66%|██████▌   | 1.06G/1.62G [00:22<00:11, 51.9MB/s]


 66%|██████▌   | 1.07G/1.62G [00:22<00:10, 53.5MB/s]


 67%|██████▋   | 1.08G/1.62G [00:22<00:10, 56.4MB/s]


 67%|██████▋   | 1.08G/1.62G [00:22<00:10, 56.5MB/s]


 67%|██████▋   | 1.09G/1.62G [00:22<00:09, 56.8MB/s]


 68%|██████▊   | 1.10G/1.62G [00:22<00:09, 58.1MB/s]


 68%|██████▊   | 1.11G/1.62G [00:22<00:09, 58.4MB/s]


 69%|██████▉   | 1.11G/1.62G [00:23<00:09, 57.9MB/s]


 69%|██████▉   | 1.12G/1.62G [00:23<00:09, 57.6MB/s]


 70%|██████▉   | 1.13G/1.62G [00:23<00:08, 58.9MB/s]


 70%|███████   | 1.13G/1.62G [00:23<00:08, 58.1MB/s]


 71%|███████   | 1.14G/1.62G [00:23<00:08, 58.4MB/s]


 71%|███████   | 1.15G/1.62G [00:23<00:08, 58.9MB/s]


 71%|███████▏  | 1.16G/1.62G [00:23<00:08, 58.4MB/s]


 72%|███████▏  | 1.16G/1.62G [00:23<00:08, 58.7MB/s]


 72%|███████▏  | 1.17G/1.62G [00:24<00:08, 58.2MB/s]


 73%|███████▎  | 1.18G/1.62G [00:24<00:08, 59.0MB/s]


 73%|███████▎  | 1.18G/1.62G [00:24<00:07, 58.5MB/s]


 74%|███████▎  | 1.19G/1.62G [00:24<00:07, 58.5MB/s]


 74%|███████▍  | 1.20G/1.62G [00:24<00:07, 59.3MB/s]


 75%|███████▍  | 1.21G/1.62G [00:24<00:07, 58.7MB/s]


 75%|███████▍  | 1.21G/1.62G [00:24<00:07, 58.7MB/s]


 75%|███████▌  | 1.22G/1.62G [00:24<00:07, 59.3MB/s]


 76%|███████▌  | 1.23G/1.62G [00:25<00:07, 59.0MB/s]


 76%|███████▋  | 1.23G/1.62G [00:25<00:06, 58.9MB/s]


 77%|███████▋  | 1.24G/1.62G [00:25<00:06, 59.4MB/s]


 77%|███████▋  | 1.25G/1.62G [00:25<00:06, 59.0MB/s]


 78%|███████▊  | 1.25G/1.62G [00:25<00:06, 58.9MB/s]


 78%|███████▊  | 1.26G/1.62G [00:25<00:06, 58.3MB/s]


 79%|███████▊  | 1.27G/1.62G [00:25<00:06, 58.7MB/s]


 79%|███████▉  | 1.28G/1.62G [00:26<00:06, 58.6MB/s]


 79%|███████▉  | 1.28G/1.62G [00:26<00:06, 58.8MB/s]


 80%|███████▉  | 1.29G/1.62G [00:26<00:06, 58.4MB/s]


 80%|████████  | 1.30G/1.62G [00:26<00:05, 59.1MB/s]


 81%|████████  | 1.30G/1.62G [00:26<00:05, 58.4MB/s]


 81%|████████  | 1.31G/1.62G [00:26<00:05, 58.9MB/s]


 82%|████████▏ | 1.32G/1.62G [00:26<00:05, 57.7MB/s]


 82%|████████▏ | 1.33G/1.62G [00:26<00:05, 55.2MB/s]


 82%|████████▏ | 1.33G/1.62G [00:27<00:05, 55.5MB/s]


 83%|████████▎ | 1.34G/1.62G [00:27<00:05, 55.2MB/s]


 83%|████████▎ | 1.35G/1.62G [00:27<00:05, 55.5MB/s]


 84%|████████▎ | 1.35G/1.62G [00:27<00:05, 55.8MB/s]


 84%|████████▍ | 1.36G/1.62G [00:27<00:04, 57.9MB/s]


 84%|████████▍ | 1.37G/1.62G [00:27<00:05, 51.5MB/s]


 85%|████████▍ | 1.37G/1.62G [00:27<00:04, 56.7MB/s]


 85%|████████▌ | 1.38G/1.62G [00:27<00:04, 59.9MB/s]


 86%|████████▌ | 1.38G/1.62G [00:28<00:04, 58.1MB/s]


 86%|████████▌ | 1.39G/1.62G [00:28<00:04, 54.4MB/s]


 86%|████████▋ | 1.40G/1.62G [00:28<00:04, 55.7MB/s]


 87%|████████▋ | 1.40G/1.62G [00:28<00:04, 55.4MB/s]


 87%|████████▋ | 1.41G/1.62G [00:28<00:03, 68.2MB/s]


 88%|████████▊ | 1.42G/1.62G [00:28<00:03, 64.6MB/s]


 88%|████████▊ | 1.43G/1.62G [00:28<00:03, 63.6MB/s]


 89%|████████▊ | 1.43G/1.62G [00:28<00:03, 61.8MB/s]


 89%|████████▉ | 1.44G/1.62G [00:29<00:03, 58.6MB/s]


 89%|████████▉ | 1.45G/1.62G [00:29<00:03, 58.5MB/s]


 90%|████████▉ | 1.45G/1.62G [00:29<00:03, 58.0MB/s]


 90%|█████████ | 1.46G/1.62G [00:29<00:02, 60.5MB/s]


 91%|█████████ | 1.46G/1.62G [00:29<00:02, 61.1MB/s]


 91%|█████████ | 1.47G/1.62G [00:29<00:02, 58.1MB/s]


 91%|█████████▏| 1.48G/1.62G [00:29<00:02, 57.8MB/s]


 92%|█████████▏| 1.48G/1.62G [00:29<00:02, 58.1MB/s]


 92%|█████████▏| 1.49G/1.62G [00:29<00:02, 55.0MB/s]


 93%|█████████▎| 1.50G/1.62G [00:30<00:02, 49.6MB/s]


 93%|█████████▎| 1.50G/1.62G [00:30<00:02, 52.5MB/s]


 93%|█████████▎| 1.51G/1.62G [00:30<00:02, 54.0MB/s]


 94%|█████████▎| 1.51G/1.62G [00:30<00:01, 56.2MB/s]


 94%|█████████▍| 1.52G/1.62G [00:30<00:01, 54.7MB/s]


 94%|█████████▍| 1.53G/1.62G [00:30<00:01, 55.5MB/s]


 95%|█████████▍| 1.53G/1.62G [00:30<00:01, 58.6MB/s]


 95%|█████████▌| 1.54G/1.62G [00:30<00:01, 58.7MB/s]


 96%|█████████▌| 1.55G/1.62G [00:31<00:01, 59.5MB/s]


 96%|█████████▌| 1.55G/1.62G [00:31<00:01, 57.1MB/s]


 96%|█████████▋| 1.56G/1.62G [00:31<00:01, 58.6MB/s]


 97%|█████████▋| 1.56G/1.62G [00:31<00:00, 59.6MB/s]


 97%|█████████▋| 1.57G/1.62G [00:31<00:00, 56.8MB/s]


 98%|█████████▊| 1.58G/1.62G [00:31<00:00, 59.5MB/s]


 98%|█████████▊| 1.58G/1.62G [00:31<00:00, 58.8MB/s]


 98%|█████████▊| 1.59G/1.62G [00:31<00:00, 59.0MB/s]


 99%|█████████▉| 1.60G/1.62G [00:31<00:00, 59.6MB/s]


 99%|█████████▉| 1.60G/1.62G [00:32<00:00, 57.5MB/s]


100%|█████████▉| 1.61G/1.62G [00:32<00:00, 57.5MB/s]


100%|██████████| 1.62G/1.62G [00:32<00:00, 53.7MB/s]

Data source import complete.

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [ ]:
import os
import transformers
import tokenizers
import numpy as np
import pandas as pd
import pickle
import gc
import os
import unicodedata

import torch
import transformers

import matplotlib.pyplot as plt

from tqdm.auto import tqdm

print("Transformers:", transformers.__version__)
print("Tokenizers:", tokenizers.__version__)

Transformers: 5.13.1
Tokenizers: 0.22.2

In [ ]:
import wandb

wandb.login(key="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")

wandb.init(
    project="24f3004935-t22026",
    name = 'deberta_lr_2e5_run'
)

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: 24f3004935 (24f3004935-dl-genai-project) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

## Debert v3 large

In [ ]:
train = pd.read_csv(
    "/content/train.csv"
)

print("Shape:", train.shape)
print("Columns:", train.columns.tolist())

Shape: (2000, 8)
Columns: ['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer']

In [ ]:
import re

def normalize_question(text):
    text = str(text).lower().strip()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[^\w\s]", "", text)
    return text


train["question_key"] = train["prompt"].apply(normalize_question)

print("Before:", len(train))

train = (
    train
    .drop_duplicates(subset="question_key")
    .drop(columns="question_key")
    .reset_index(drop=True)
)

print("After:", len(train))

Before: 2000
After: 1758

In [ ]:
label_map = {
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "E": 4
}

train["label"] = train["answer"].map(label_map)

train[["answer", "label"]].head(10)

  answer  label
0      B      1
1      A      0
2      C      2
3      B      1
4      A      0
5      C      2
6      E      4
7      A      0
8      A      0
9      A      0

## train/val

In [ ]:
from sklearn.model_selection import train_test_split

train_df, valid_df = train_test_split(
    train,
    test_size=0.2,
    random_state=42,
    stratify=train["label"]
)

print("Train:", train_df.shape)
print("Validation:", valid_df.shape)

Train: (1406, 9)
Validation: (352, 9)

## Tokenizing

In [ ]:
import os

os.environ["HF_TOKEN"] = "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"
os.environ["HF_HUB_DISABLE_XET"] = "1"
os.environ["HF_HUB_DOWNLOAD_TIMEOUT"] = "600"

print("HF token set:", bool(os.environ.get("HF_TOKEN")))

HF token set: True

In [ ]:
!pip install -q kagglehub

In [ ]:
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

!pip install -q kagglehub

import kagglehub
from transformers import DebertaV2Tokenizer, DebertaV2ForMultipleChoice

# Download the Kaggle model
MODEL_PATH = kagglehub.model_download(
    "illuminatep/deberta-v3-plain/transformers/large/1"
)

print("Model path:", MODEL_PATH)

# Load tokenizer and model
tokenizer = DebertaV2Tokenizer.from_pretrained(MODEL_PATH)
print("Tokenizer loaded.")

model = DebertaV2ForMultipleChoice.from_pretrained(MODEL_PATH)
print(f"Model loaded. Params: {sum(p.numel() for p in model.parameters())/1e6:.1f}M")

Model path: /kaggle/input/deberta-v3-plain/transformers/large/1
Tokenizer loaded.

Loading weights:   0%|          | 0/390 [00:00<?, ?it/s]

[transformers] DebertaV2ForMultipleChoice LOAD REPORT from: /kaggle/input/deberta-v3-plain/transformers/large/1
Key                 | Status  |
--------------------+---------+-
classifier.bias     | MISSING |
classifier.weight   | MISSING |
pooler.dense.weight | MISSING |
pooler.dense.bias   | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model loaded. Params: 435.1M

## MAP@3

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, f1_score
import numpy as np

def map_at_3(predictions, labels):
    map_sum = 0
    pred = np.argsort(-np.array(predictions), axis=1)[:, :3]

    for x, y in zip(pred, labels):
        z = [1/i if y == j else 0 for i, j in zip([1, 2, 3], x)]
        map_sum += np.sum(z)

    return map_sum / len(predictions)


def compute_metrics(p):
    predictions = p.predictions
    labels = p.label_ids

    preds = np.argmax(predictions, axis=1)

    return {
        "accuracy": accuracy_score(labels, preds),
        "precision": precision_score(
            labels,
            preds,
            average="macro",
            zero_division=0
        ),
        "f1": f1_score(
            labels,
            preds,
            average="macro"
        ),
        "map@3": map_at_3(predictions, labels)
    }

## Train and save

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/deberta-v3-large-mcq",

    num_train_epochs=2,
    learning_rate=2e-5,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,

    logging_strategy="steps",
    logging_steps=25,

    eval_strategy="steps",
    eval_steps=25,

    save_strategy="no",

    report_to="wandb",

    remove_unused_columns=False,
    seed=42
)

In [ ]:
import random
from torch.utils.data import Dataset


class MCQDataset(Dataset):

    def __init__(
        self,
        df,
        tokenizer,
        question_dropout=0.5
    ):
        self.df = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.question_dropout = question_dropout


    def __len__(self):
        return len(self.df)


    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        question = row["prompt"]

        if random.random() < self.question_dropout:
            question = ""

        options = [
            row["A"],
            row["B"],
            row["C"],
            row["D"],
            row["E"]
        ]

        encoded = self.tokenizer(
            [question] * 5,
            options,
            truncation=True,
            max_length=512,
            padding=False,
            return_token_type_ids = False
        )

        encoded["label"] = int(row["label"])

        return encoded

In [ ]:
from datasets import Dataset

train_dataset = MCQDataset(
    train_df,
    tokenizer,
    question_dropout=0.5
)

valid_dataset = MCQDataset(
    valid_df,
    tokenizer,
    question_dropout=0.0
)

print("Train:", len(train_dataset))
print("Valid:", len(valid_dataset))

Train: 1406
Valid: 352

In [ ]:
# tokenized_dataset = train_dataset.map(
#     preprocess_function,
#     remove_columns=train_dataset.column_names
# )

# tokenized_dataset_valid = valid_dataset.map(
#     preprocess_function,
#     remove_columns=valid_dataset.column_names
# )

# print(tokenized_dataset)
# print(tokenized_dataset_valid)

In [ ]:
from transformers import DataCollatorForMultipleChoice

data_collator = DataCollatorForMultipleChoice(
    tokenizer=tokenizer
)

print("Data collator ready")

Data collator ready

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

# trainer.save_model(
#     "/kaggle/working/model_v2"
# )

# tokenizer.save_pretrained(
#     "/kaggle/working/model_v2"
# )
wandb.finish()

In [ ]:
# !cd /kaggle/working && zip -r model_v2.zip model_v2

In [ ]:
# !ls -lh /kaggle/working/model_v2.zip

In [ ]:
# !ls -lh /kaggle/working